<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsAanvvoorwaardenMedbewEnTekstblok as BaseGsAanvvoorwaardenMedbewEnTekstblok;

class GsAanvvoorwaardenMedbewEnTekstblok extends BaseGsAanvvoorwaardenMedbewEnTekstblok
{
}
