<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsAanvvoorwaardenMedbewEnTekstblokQuery as BaseGsAanvvoorwaardenMedbewEnTekstblokQuery;

class GsAanvvoorwaardenMedbewEnTekstblokQuery extends BaseGsAanvvoorwaardenMedbewEnTekstblokQuery
{
}
