<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsBewakingenTeControlerenIndicatiesQuery as BaseGsBewakingenTeControlerenIndicatiesQuery;

class GsBewakingenTeControlerenIndicatiesQuery extends BaseGsBewakingenTeControlerenIndicatiesQuery
{
}
