<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsBewakingenTeControlerenIndicaties as BaseGsBewakingenTeControlerenIndicaties;

class GsBewakingenTeControlerenIndicaties extends BaseGsBewakingenTeControlerenIndicaties
{
}
