<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsCoderingGedifferentieerdeTarieven as BaseGsCoderingGedifferentieerdeTarieven;

class GsCoderingGedifferentieerdeTarieven extends BaseGsCoderingGedifferentieerdeTarieven
{
}
