<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsCoderingGedifferentieerdeTarievenQuery as BaseGsCoderingGedifferentieerdeTarievenQuery;

class GsCoderingGedifferentieerdeTarievenQuery extends BaseGsCoderingGedifferentieerdeTarievenQuery
{
}
