<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsCodestelselZrsOnderlingVerbandQuery as BaseGsCodestelselZrsOnderlingVerbandQuery;

class GsCodestelselZrsOnderlingVerbandQuery extends BaseGsCodestelselZrsOnderlingVerbandQuery
{
}
