<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsDoseringenUitzonderingenOpBasisQuery as BaseGsDoseringenUitzonderingenOpBasisQuery;

class GsDoseringenUitzonderingenOpBasisQuery extends BaseGsDoseringenUitzonderingenOpBasisQuery
{
}
