<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsDoseringenUitzonderingenOpBasis as BaseGsDoseringenUitzonderingenOpBasis;

class GsDoseringenUitzonderingenOpBasis extends BaseGsDoseringenUitzonderingenOpBasis
{
}
