<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsDoseringenBasisartikelkeuzeQuery as BaseGsDoseringenBasisartikelkeuzeQuery;

class GsDoseringenBasisartikelkeuzeQuery extends BaseGsDoseringenBasisartikelkeuzeQuery
{
}
