<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsEnkelvoudigeToedieningswegenHpkQuery as BaseGsEnkelvoudigeToedieningswegenHpkQuery;

class GsEnkelvoudigeToedieningswegenHpkQuery extends BaseGsEnkelvoudigeToedieningswegenHpkQuery
{
}
