<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsEnkelvoudigeToedieningswegenHpk as BaseGsEnkelvoudigeToedieningswegenHpk;

class GsEnkelvoudigeToedieningswegenHpk extends BaseGsEnkelvoudigeToedieningswegenHpk
{
}
