<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsGekoppeldeTekstenUitWciaTabel25 as BaseGsGekoppeldeTekstenUitWciaTabel25;

class GsGekoppeldeTekstenUitWciaTabel25 extends BaseGsGekoppeldeTekstenUitWciaTabel25
{
}
