<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsIndicatiesBijSupplementaireProductenQuery as BaseGsIndicatiesBijSupplementaireProductenQuery;

class GsIndicatiesBijSupplementaireProductenQuery extends BaseGsIndicatiesBijSupplementaireProductenQuery
{
}
