<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsIndicatiesBijSupplementaireProducten as BaseGsIndicatiesBijSupplementaireProducten;

class GsIndicatiesBijSupplementaireProducten extends BaseGsIndicatiesBijSupplementaireProducten
{
}
