<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsKoppelingZrsMetExterneCodesQuery as BaseGsKoppelingZrsMetExterneCodesQuery;

class GsKoppelingZrsMetExterneCodesQuery extends BaseGsKoppelingZrsMetExterneCodesQuery
{
}
