<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsLogistiekeVerpakkingsinformatie as BaseGsLogistiekeVerpakkingsinformatie;

class GsLogistiekeVerpakkingsinformatie extends BaseGsLogistiekeVerpakkingsinformatie
{
}
