<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsLogistiekeVerpakkingsinformatieQuery as BaseGsLogistiekeVerpakkingsinformatieQuery;

class GsLogistiekeVerpakkingsinformatieQuery extends BaseGsLogistiekeVerpakkingsinformatieQuery
{
}
