<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsMedicatieBewakingKoppelenMetZrsQuery as BaseGsMedicatieBewakingKoppelenMetZrsQuery;

class GsMedicatieBewakingKoppelenMetZrsQuery extends BaseGsMedicatieBewakingKoppelenMetZrsQuery
{
}
