<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsMedicatieBewakingKoppelenMetZrs as BaseGsMedicatieBewakingKoppelenMetZrs;

class GsMedicatieBewakingKoppelenMetZrs extends BaseGsMedicatieBewakingKoppelenMetZrs
{
}
