<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsMfbWaardelijstenMeerdereNiveaus as BaseGsMfbWaardelijstenMeerdereNiveaus;

class GsMfbWaardelijstenMeerdereNiveaus extends BaseGsMfbWaardelijstenMeerdereNiveaus
{
}
