<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsMfbWaardelijstenMeerdereNiveausQuery as BaseGsMfbWaardelijstenMeerdereNiveausQuery;

class GsMfbWaardelijstenMeerdereNiveausQuery extends BaseGsMfbWaardelijstenMeerdereNiveausQuery
{
}
