<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsMfbKoppelingExterneCoderingenQuery as BaseGsMfbKoppelingExterneCoderingenQuery;

class GsMfbKoppelingExterneCoderingenQuery extends BaseGsMfbKoppelingExterneCoderingenQuery
{
}
