<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsMfbVraagFunctieWaardelijstQuery as BaseGsMfbVraagFunctieWaardelijstQuery;

class GsMfbVraagFunctieWaardelijstQuery extends BaseGsMfbVraagFunctieWaardelijstQuery
{
}
