<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsMfbVervangingMedicatiebewakingQuery as BaseGsMfbVervangingMedicatiebewakingQuery;

class GsMfbVervangingMedicatiebewakingQuery extends BaseGsMfbVervangingMedicatiebewakingQuery
{
}
