<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsMfbTriggerGeneesmiddelkeuzeQuery as BaseGsMfbTriggerGeneesmiddelkeuzeQuery;

class GsMfbTriggerGeneesmiddelkeuzeQuery extends BaseGsMfbTriggerGeneesmiddelkeuzeQuery
{
}
