<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsRelatieOngewensteGroepensnkQuery as BaseGsRelatieOngewensteGroepensnkQuery;

class GsRelatieOngewensteGroepensnkQuery extends BaseGsRelatieOngewensteGroepensnkQuery
{
}
