<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsStamnaamStamtoedieningswegQuery as BaseGsStamnaamStamtoedieningswegQuery;

class GsStamnaamStamtoedieningswegQuery extends BaseGsStamnaamStamtoedieningswegQuery
{
}
