<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsSupplementaireProductenMetNzaMaximumtarief as BaseGsSupplementaireProductenMetNzaMaximumtarief;

class GsSupplementaireProductenMetNzaMaximumtarief extends BaseGsSupplementaireProductenMetNzaMaximumtarief
{
}
