<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsSupplementaireProductenMetNzaMaximumtariefQuery as BaseGsSupplementaireProductenMetNzaMaximumtariefQuery;

class GsSupplementaireProductenMetNzaMaximumtariefQuery extends BaseGsSupplementaireProductenMetNzaMaximumtariefQuery
{
}
