<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsSupplementaireProductenHistorie as BaseGsSupplementaireProductenHistorie;

class GsSupplementaireProductenHistorie extends BaseGsSupplementaireProductenHistorie
{
}
