<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsSupplementaireProductenHistorieQuery as BaseGsSupplementaireProductenHistorieQuery;

class GsSupplementaireProductenHistorieQuery extends BaseGsSupplementaireProductenHistorieQuery
{
}
