<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsVerkorteAddonIndicatietekstenQuery as BaseGsVerkorteAddonIndicatietekstenQuery;

class GsVerkorteAddonIndicatietekstenQuery extends BaseGsVerkorteAddonIndicatietekstenQuery
{
}
