<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsVoorschrijfprIdentificerendeVeldenQuery as BaseGsVoorschrijfprIdentificerendeVeldenQuery;

class GsVoorschrijfprIdentificerendeVeldenQuery extends BaseGsVoorschrijfprIdentificerendeVeldenQuery
{
}
