<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsVoorschrijfprGeneesmiddelIdentificQuery as BaseGsVoorschrijfprGeneesmiddelIdentificQuery;

class GsVoorschrijfprGeneesmiddelIdentificQuery extends BaseGsVoorschrijfprGeneesmiddelIdentificQuery
{
}
