<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\Base\GsVoorschrijfprIdentificerendeVelden as BaseGsVoorschrijfprIdentificerendeVelden;

class GsVoorschrijfprIdentificerendeVelden extends BaseGsVoorschrijfprIdentificerendeVelden
{
}
